import type { Metadata } from 'next'
import { Blinker } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const blinker = Blinker({ subsets: ['latin'], weight: ['400', '600'] })

export const metadata: Metadata = {
  title: 'Diamond Heart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={blinker.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
